### ISSUE TITLE
error showClientRate 

### ISSUE THREAD

**Issue by pitchx** [bugsounet/MMM-Freebox#3]
with param showClientRate in config.js i've this error :

```
[ERROR]  (node:4364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tx_bytes_rate' of undefined
    at macList.forEach.mac (/home/pi/MagicMirror/modules/MMM-Freebox/node_helper.js:256:50)
    at Array.forEach (<anonymous>)
    at Class.makeResult (/home/pi/MagicMirror/modules/MMM-Freebox/node_helper.js:254:25)
    at Freebox.Freebox_OS.then (/home/pi/MagicMirror/modules/MMM-Freebox/node_helper.js:109:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[18:19:00.239] [ERROR]  (node:4364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[18:19:00.240] [ERROR]  (node:4364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bugsounet** [comment]
Je vais inspecter, je reviens vers vous dès que possible

**Comment by bugsounet** [comment]
je viens d'inspecter l'erreur par rapport au code et a ce que sort l'api de la freebox.
Ce que je ne comprend pas c'est que l'api de la freebox sort systématiquement cette valeur `tx_bytes_rate` (je ne scan pas sa presence pour cela)
Elle sort obligatoirement cette valeur a chaques ports ethernet (qu'il y a quelque chose de connecté ou pas)
D'ou je me pose la question ...
quel type de freebox avez-vous ?
votre Freebox est elle a jour ?
un redémarrage electrique serai t'il possible afin de vérifier si il y aurai un nouveau firmware ?

dans l'attente de votre réponse,
Cédric

**Comment by pitchx** [comment]
Bonjour,

J'ai la freebox devialet, complètement à jour plusieurs hard reboot fait.

Merci encore

**Comment by pitchx** [comment]
En complément de mon post voici des screen de mon interface freebox sur les
débit wifi et lan
[image: lan.jpg]
[image: wifi.jpg]

**Comment by bugsounet** [comment]
j'ai mis a jour, si vous pouvez me dire ce qu'il cela fonctionne.
j'ai mis en place un systeme de log pour moi voir ce qu'il se passe au cas ou

Désolé, j'ai pas la devialet :(

**Comment by pitchx** [comment]
yes bravo quelle efficacité,

ça marche plutôt nickel sauf pour le player mais je pense que c'est normal
[image: image.png]
